import type { BacklogEntry } from './types'

export const newChangesBacklogData: BacklogEntry[] = [
  {
    id: 'ODL-I2513',
    title: 'CR - 70 - Display Additional Remark Fields in Job Charge Filtering Panel',
    hours: 35,
    tag: 'new feature',
  },
  {
    id: 'T-103',
    title: 'CR - 23 - System Log Module.',
    hours: 225,
    tag: 'new feature',
  },
  {
    id: 'ODL-I1050',
    title: 'CR 34 - Assignment Of Multiple Customers & Shipper/Plant To Customer Users.',
    hours: 48,
    tag: 'new feature',
  },
  {
    id: 'T-104',
    title: 'CR - 45 - Incident Tracker Module',
    hours: 54,
    tag: 'new feature',
  },
  {
    id: 'T-105',
    title: 'CR - 50 - Addition of a new flag status called flag accept.',
    hours: 24,
    tag: 'new feature',
  },
  {
    id: 'T-106',
    title: 'CR - 51 - Option to upload booking wise charges for the transporters.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-107',
    title: 'CR - 52 - Addition of another column in the job monitoring to capture the additional mobile number.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-108',
    title: 'CR - 53 - Option to deactivate the vouchers, invoice CDNs and vouchers CDNs.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-110',
    title: 'CR - 55 - Client requests that when “customer” is entered, the System User list currently shows only customer-related users, but they need all users to be visible in the System User list.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-111',
    title: 'CR - 56 - Client requested an option to get the IP address used to create the booking number (to identify whether it was created using a personal or company network).',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-112',
    title: 'CR - 57 -  Driver Mobile Application Development.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-113',
    title: 'CR - 58 - Change booking times for completed jobs.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-114',
    title: 'CR - 59 - Plant change, location change, vehicle type change, invoice change, billing update, supplier name change, and customer change at any job status.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-115',
    title: 'CR - 61 - Finance confirmation rollback and EV confirmation rollback.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-116',
    title: 'CR - 62 - Edit and delete updated charges after finance confirmation.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-117',
    title: 'CR - 63 - Booking recall.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-118',
    title: 'CR - 64 - Negotiation updates after operation confirmation - Add permissions.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-119',
    title: 'CR - 65 - Operation remark update and creator remark update at any job status.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-120',
    title: 'CR - 66 - KM deviation updates.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-122',
    title: 'CR - 68 - Booking edit after EV generation.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'T-123',
    title: 'CR - 69 - Operation Confirm Bulk remove.',
    hours: 15,
    tag: 'new feature',
  },
  {
    id: 'ODL-I2627',
    title: 'CR Vehicle utilization detail report.',
    hours: 50,
    tag: 'new feature',
  },
  {
    id: 'ODL-I2627',
    title: 'CR Add the actual arrival time column to the on-time delivery report..',
    hours: 50,
    tag: 'new feature',
  },
  {
    id: 'ODL-I2628',
    title: 'CR Add a separate column for Status and row for MTD AVG in summery report..',
    hours: 50,
    tag: 'new feature',
  },
]